### ISSUE TITLE
wand.exceptions.PolicyError raised during Cropping

### ISSUE THREAD

**Issue by mr-ubik** [GjjvdBurg/arxiv2remarkable#4]
## Steps to reproduce:

1) Clone the repository
2) Install the Python Dependencies
3) Try to sync https://arxiv.org/abs/1810.06339
4) Exception raised after/during the PDF cropping stage

## STD Output

```std
Traceback (most recent call last):
  File "arxiv2remarkable.py", line 837, in <module>
    main()
  File "arxiv2remarkable.py", line 833, in main
    prov.run(args.input, filename=args.filename)
  File "arxiv2remarkable.py", line 317, in run
    intermediate_fname = op(intermediate_fname)
  File "arxiv2remarkable.py", line 144, in crop_pdf
    status = cropper.crop(margins=15)
  File "arxiv2remarkable.py", line 610, in crop
    return self.process_file(self.crop_page, margins=margins)
  File "arxiv2remarkable.py", line 617, in process_file
    status = page_func(page_idx, *args, **kwargs)
  File "arxiv2remarkable.py", line 630, in crop_page
    return self.process_page(page_idx, self.get_bbox, margins=margins)
  File "arxiv2remarkable.py", line 646, in process_page
    bbox = bbox_func(tmpfname, *args, **kwargs)
  File "arxiv2remarkable.py", line 678, in get_bbox
    im = pdf.pages[0].to_image(resolution=resolution)
  File "/home/ubik/.local/lib/python3.7/site-packages/pdfplumber/page.py", line 258, in to_image
    return PageImage(self, **kwargs)
  File "/home/ubik/.local/lib/python3.7/site-packages/pdfplumber/display.py", line 44, in __init__
    resolution
  File "/home/ubik/.local/lib/python3.7/site-packages/pdfplumber/display.py", line 25, in get_page_image
    with wand.image.Image(filename=page_path, resolution=resolution) as img:
  File "/home/ubik/.local/lib/python3.7/site-packages/wand/image.py", line 7495, in __init__
    self.read(filename=filename, resolution=resolution)
  File "/home/ubik/.local/lib/python3.7/site-packages/wand/image.py", line 7884, in read
    self.raise_exception()
  File "/home/ubik/.local/lib/python3.7/site-packages/wand/resource.py", line 240, in raise_exception
    raise e
wand.exceptions.PolicyError: attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/408
```

**Comment by GjjvdBurg** [comment]
Hi @mr-ubik, thanks for reporting this! This is actually a problem with ImageMagick. You can read more about it and how to fix it here: https://stackoverflow.com/questions/52998331/imagemagick-security-policy-pdf-blocking-conversion

I'm assuming this will work so I'll close the issue, but feel free to reopen if it doesn't!

**Comment by mr-ubik** [comment]
Fantastic, thanks!
