### ISSUE TITLE
Title contains "/" leads to FileNotFoundError

### ISSUE THREAD

**Issue by aweiler** [GjjvdBurg/arxiv2remarkable#6]
If the title of the paper contains a "/", there is a FileNotFoundError. Try e.g. with http://arxiv.org/abs/1909.02568

```
2019-10-07 16:33:13 - INFO - Starting Arxiv
2019-10-07 16:33:13 - INFO - Getting paper info
2019-10-07 16:33:14 - INFO - Downloading url: http://arxiv.org/abs/1909.02568
2019-10-07 16:33:14 - INFO - Generating output filename
2019-10-07 16:33:14 - INFO - Created filename: Budnik_et_al_-_Searching_for_a_Solar_Relaxion/Scalar_With_XENON1T_and_LUX_2019.pdf
2019-10-07 16:33:14 - INFO - Downloading file at url: http://arxiv.org/pdf/1909.02568.pdf
2019-10-07 16:33:17 - INFO - Downloading url: http://arxiv.org/pdf/1909.02568.pdf
2019-10-07 16:33:17 - INFO - Removing arXiv timestamp
2019-10-07 16:33:17 - INFO - Cropping pdf file
2019-10-07 16:33:23 - INFO - Shrinking pdf file
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/shutil.py", line 566, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: 'paper_dearxiv-crop-shrink.pdf' -> 'Budnik_et_al_-_Searching_for_a_Solar_Relaxion/Scalar_With_XENON1T_and_LUX_2019.pdf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "arxiv2remarkable.py", line 846, in <module>
    main()
  File "arxiv2remarkable.py", line 842, in main
    prov.run(args.input, filename=args.filename)
  File "arxiv2remarkable.py", line 363, in run
    shutil.move(intermediate_fname, clean_filename)
  File "/usr/local/lib/python3.7/shutil.py", line 580, in move
    copy_function(src, real_dst)
  File "/usr/local/lib/python3.7/shutil.py", line 266, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.7/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'Budnik_et_al_-_Searching_for_a_Solar_Relaxion/Scalar_With_XENON1T_and_LUX_2019.pdf'
```

**Comment by GjjvdBurg** [comment]
Thanks for the bug report @aweiler! This should be fixed in the latest update to the script. I'll get to the other issue you raised soon :)

**Comment by aweiler** [comment]
Thanks so much, this fixes it!  (I had to remember to redo the docker build). 

I am using your awesome script everyday and I am recommending it at my university.

**Comment by GjjvdBurg** [comment]
Thanks @aweiler, that's great to hear!
